spring:
  application:
    name: ISH-ApplicationRegistartion

  datasource:
    url: jdbc:mysql:///jrtp-701-ISH_DB
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


server:
  port: 9091
ar:
  ssa-web:
      url: http://localhost:9090/ssa-web-api/find/{ssn}
  state: califorina